### ISSUE TITLE
Documentation: some output isn't labeled "Out [#]"

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-python-stix2#105]
This seems confusing.

Example bottom of https://stix2.readthedocs.io/en/latest/guide/custom.html

**Comment by gtback** [comment]
I'm not sure why this is happening. It may have to do with the difference between "print" output of Jupyter notebooks and the default behavior of displaying the output of the last statement in any block.

**Comment by clenk** [comment]
I think @gtback is right. Examples from nbsphinx (https://nbsphinx.readthedocs.io/en/0.2.14/code-cells.html) have `print()`s showing up without a "Out [#]:" label, but an expression (eg. `6 * 7`) will.

The reason some of our `print()`s do show up with that label is that we modified `print` to enable syntax highlighting if the string is JSON.

**Comment by rpiazza** [comment]
If possible it should consistent.  When I first saw that example I thought that some extra text was just randomly included - until I took a closer look at it.

**Comment by gtback** [comment]
Ah, so if `print()` is returning JSON, it will show `Out []`, but otherwise it won't. That makes more sense.
