### ISSUE TITLE
Change `allow_custom` in DataStores

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-python-stix2#108]
- [ ] `allow_custom` should be an attribute on data store/source/sink class instances, ~~and you should be able to overwrite the default in an individual method call. (e.g. you have a DataStore set up with `self.allow_custom = False`, but just this once you want to add an object with a custom property so you call `datastore.add(..., allow_custom=True`)~~
- [ ] `allow_custom` should default to `True` in DataSources; assume that only valid content was placed in the datasource. It can default to `False` in DataSinks.

**Comment by FearonChris** [comment]
FYI. unable to  `.get()` an existing object containing custom fields:

`ExtraPropertiesError: Unexpected properties for Vulnerability`

```
filesystem.py line #307:
# parse python STIX objects from the STIX object dicts
stix_objs = [parse(stix_obj_dict, allow_custom=allow_custom, version=version) for stix_obj_dict in all_data]

```
unable to pass allow_custom to .get()

**Comment by mbastian1135** [comment]
@FearonChris , Im assuming you are passing `allow_custom=True` to `.get()`?

**Comment by FearonChris** [comment]
am indeed. Its complaining about unexpected args allow_custom

**Comment by gtback** [comment]
@FearonChris are you using the latest version of python-stix2 (0.4) that was released last week?

**Comment by FearonChris** [comment]
yes

**Comment by gtback** [comment]
Are you using a CompositeDataSource? (or an Environment, which effectively does the same thing.

For me, this works:

```
import stix2
src = stix2.FileSystemSource("/path/to/cti/ATTACK/")
src.get('attack-pattern--00d0b012-8a03-410e-95de-5826bf542de6', allow_custom=True)
```

(where `cti` is [this repository](https://github.com/mitre/cti))

but this does not:

```
cs = stix2.CompositeDataSource()
cs.add_data_source(src)
cs.get('attack-pattern--00d0b012-8a03-410e-95de-5826bf542de6', allow_custom=True)
```

This is something we should fix as part of this issue.

**Comment by FearonChris** [comment]
im generating via: 

```
        stixVulnerability = self.factory.create(
                    Vulnerability,
                    **vArgs
                    )
```

with `allow_custom: True` in **vArgs. (yes i'm using an environment)

**Comment by gtback** [comment]
@FearonChris is that a separate issue? There shouldn't be any overlapping code between the `ObjectFactory.create` and `DataSource.get`. Also, are you subclassing/modifying the Environment class, or creating your own ObjectFactory? We hadn't really envisioned the subclassing use case, so I'm curious what you're trying to do. Feel free to shoot me an email at gback@mitre.org, especially if this conversation continues to veer away from `DataSource`s .

**Comment by johnwunder** [comment]
I agree that the default for data sources should be `allow_custom=True`. At the hackathon the majority of the content contained custom properties and it was hard to get `allow_custom=True` to the right places.

I would also make sure that the documentation is updated to describe how to set the attribute for data sources and data sinks.
