### ISSUE TITLE
No longer able to pass List to Bundle()

### ISSUE THREAD

**Issue by FearonChris** [oasis-open/cti-python-stix2#115]
Previously I was able to pass a list of objects to Bundle:

`Bundle(<list of sdo objects>)` with 0.4  this no longer works:

`Invalid value for Bundle 'objects': This property may only contain a dictionary or object`.

Was this an intentional change?

**Comment by gtback** [comment]
@clenk can you look at this?

**Comment by clenk** [comment]
I haven't been able to reproduce this issue. Both of the following work for me with version 0.4.0:

```b = Bundle([obj1, obj2, obj3])```
```b = Bundle(obj1, obj2, obj3)```

@FearonChris can you give us a little more context around the code that's getting the error?

**Comment by FearonChris** [comment]
Apologies it appears the issue is user error. In building test environment my identity.json SDO was missing (doh!). Hence 'None' not being a dict or object (it wasn't available).  I was implementing  via:

```
list = [sdo, sdo, sdo]
b = Bundle(list)
```

Is there a case for producing incomplete Bundles?  This might blur the line with the spec but as far as i'm aware the SDO isnt an 'official' SDO.

**Comment by clenk** [comment]
Sorry, I don't think I understand. What do you mean by incomplete Bundles? We could add a check to skip over any 'None' objects passed to the Bundle constructor, but that could cause the library to fail silently. I'm inclined to leave it raising an exception so the user knows that something unexpected happened.

**Comment by clenk** [comment]
I'm going to close this as the original issue was user error and there hasn't been any activity for several months, but if there's something we still need to address, feel free to re-open.
