### ISSUE TITLE
Allow generic custom objects

### ISSUE THREAD

**Issue by johnwunder** [oasis-open/cti-python-stix2#118]
Right now the only way to support custom objects is to create new classes with an annotation, which means that you need to know about all possible custom objects that you'll get. Many people might not, though...they connect to IBM and if IBM suddenly decides to create a new type of custom object they're not going to know ahead of time.

python-stix2 should at least have an option to create generic custom objects. This would minimally let you pull from a TAXII collection that includes custom objects, even if you can't do anything with the custom objects themselves. As it is, though, you can't even run the query because it tries and fails to parse all of the objects that are returned.

**Comment by gtback** [comment]
Good idea, @johnwunder, thanks!

**Comment by mbastian1135** [comment]
@gtback, @clenk   - proposed hack to do this:

Enable this capability via the existing @CustomObject API but with a special "x-generic-custom-allow-all" type. The dummy created custom object class gets created and registered in the OBJ_MAP. Then in parse(), if the object mapping (of any random custom object) results in a key error, parse() will then check if "x-generic-custom-allow-all" exists in OBJ_MAP, if so return data (un-parsed)

**Comment by gtback** [comment]
I don't like anything that starts with "proposed hack" :-P

Right now `allow_custom` really means "allow custom properties on known STIX object types". What if we expand it to also allow custom object types, even those that aren't explicitly registered? The change would be around [here](https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/core.py#L101-L105). We *could* use separate flags for these (so you could allow custom properties, but not custom objects, for instance), but this seems like over-engineering at this point.

**Comment by mbastian1135** [comment]
That's simpler and definitely less hacky ;). Sounds reasonable, we can always change flags in the future if a user specifically mentions it.

**Comment by gtback** [comment]
This should be fixed by #153
