### ISSUE TITLE
Add attributes to Classes listed in the API Reference

### ISSUE THREAD

**Issue by awest1339** [oasis-open/cti-python-stix2#120]
* For the readthedocs documentation, it would be nice if the classes had their attributes listed with them
* https://stix2.readthedocs.io/en/latest/api_ref.html
* E.g. for https://stix2.readthedocs.io/en/latest/api/stix2.v20.sdo.html#stix2.v20.sdo.AttackPattern, being able to see the expected attributes for an instance of AttackPattern would be helpful

**Comment by gtback** [comment]
Thanks for the suggestion, @awest1339 . Hopefully we'll get a chance to do this soon.
