### ISSUE TITLE
Add documentation on using multiple STIX versions

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-python-stix2#129]
As we get closer to supporting STIX 2.1 and 2.0 simultaneously, we need to add documentation on the best practices for managing multiple versions, depending on the goals of the code using python-stix2. 

This is roughly summarized [here](https://github.com/oasis-open/cti-python-stix2/issues/79#issuecomment-337736097).

**Comment by clenk** [comment]
@emmanvg did write [this](http://stix2.readthedocs.io/en/latest/guide/ts_support.html). Does that fill this need? Do we need to title it differently to be easier to find?

**Comment by emmanvg** [comment]
Yeah, the link @clenk shared is precisely that summary about how to use more than one version at the same time. Right now, the library will default to use the latest version. Also, I have a few changes on my local fork that we can merge into cti-python-stix2 (stix2.1 branch)

**Comment by gtback** [comment]
Nope, that's great. I forgot we had that documentation.
