### ISSUE TITLE
TAXIICollectionSink.add() should prefer _STIXBase objects

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-python-stix2#134]
The `TAXIICollectionSink.add()` function should prefer to accept _STIXBase objects (Bundles, or STIX Data Types with IDs).
 - If a Bundle, just call **`serialize(pretty=False)`**. We don’t want the overhead of pretty-printing and sorting keys for what should be a machine-to-machine transfer.
 - If a STIX object, wrap in a Bundle first before calling `serialize()`.

The `TAXIICollectionSink.add()` function MAY (?) also accept dictionaries representing those types of STIX data, and call `parse()`.
 - If we call `parse()`, we don’t want to allow custom properties (if you needed custom properties, you should build your own _STIXBase first). 
 - This `parse()` won’t call json.load/loads, since it’s already a dict, but see #135 for splitting up `parse()`. 
 - We can probably call `parse()` here and not pass it as a dictionary to `taxii2client` (we aren’t loading JSON)

**Comment by mbastian1135** [comment]
#135 is highly binded to this design proposal
