### ISSUE TITLE
When you use the query method, the “type” property should be checked

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-python-stix2#136]
Since a STIX type name can only use ‘-’s, we should check to make sure there is no '_' in it (an easy to make typo).

Maybe for all uses of a type name...

**Comment by clenk** [comment]
(This was originally brought up in the context of the `query()` method on DataStores.)

**Comment by mbastian1135** [comment]
@rpiazza - Hey Rich, could you elaborate for me? Does this mean checking the 'type' field in a Filter when it is passed to a DataStore ( or when the FIlter is created)? Or checking the 'type' field of every STIX object searched over?  Or a check when creating a STIX CustomObject?

**Comment by rpiazza** [comment]
Yes - just if it is part of a query.

**Comment by gtback** [comment]
Fixed by #147
