### ISSUE TITLE
Rundown status of existing issue: FileSystem query bug

### ISSUE THREAD

**Issue by mbastian1135** [oasis-open/cti-python-stix2#138]
Bug: When querying FileSystem, it came back with JSON parse error. Specifically had to use a filter with “type” field to work. @mbastian1135 was trying to reproduce this, but having problems

**Comment by mbastian1135** [comment]
So  based on the comment from the user, I think this may be what was triggering (https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/core.py#L99) . Which would mean the FileSystemSource was processing an ill-formed STIX object.  If this is the case, should we ignore ill-formed STIX objects when retrieving or is this operating as we would expect? (I think the latter) 

@clenk @gtback

**Comment by gtback** [comment]
I ran into a problem once where random non-STIX files (in my case, the .DS_Store files on macOS) were causing problems. We should try (somehow?) to distinguish between non-JSON files and invalid STIX files. Maybe the `type` check does a good enough job of this?
