### ISSUE TITLE
New Feature Request: Filter functions (and docs for it)

### ISSUE THREAD

**Issue by mbastian1135** [oasis-open/cti-python-stix2#140]
Feature request: Ability to do “OR”’s in filtering. Generalizing this request to just more pattern-like ability within filtering. (complicated feature we punted on but should think more about).  To include functionality such as:
- regular-expression searches
- case-insensitive searches
- enable dereferencing within Filters, to allow eg. created_by_ref.name

Leaning towards just allowing the capability to pass a filter function (function which takes a STIX object and returns a bool) in addition to Filter object. If we do this, we’ll want to have some examples.

**Comment by mbastian1135** [comment]
Dev Meeting 18 April 2018

Punt on this enhancement for now. The functionality can be done just as easy on the user side and does not require being pulled into the library.

**Comment by clenk** [comment]
Since we decided to hold off on this, I'm closing this issue. But if someone reading this would greatly benefit from having this feature, please open a new issue or PR and we'll reconsider!
