### ISSUE TITLE
Using ArangoDB instead of SQL

### ISSUE THREAD

**Issue by oliveriandrea** [oasis-open/cti-python-stix2#149]
Hi, why you don't use ArangoDB instead of an SQL db in order to save STIX 2.0 documents? It support natively JSON and permits to construct free structure graph on records and query for that

**Comment by clenk** [comment]
Hi @oliveriandrea, I'm not aware of any SQL database in use in this library. However, we would welcome a Pull Request for a [DataStore ](https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/datastore/__init__.py) for ArangoDB if you or someone else were to make one!

**Comment by clenk** [comment]
I'm going to go ahead and close this for now, but feel free to re-open if I missed something.
