### ISSUE TITLE
Forgot variable assignment in format_datetime()

### ISSUE THREAD

**Issue by chisholm** [oasis-open/cti-python-stix2#15]
The localization in the `except` part of the try-except isn't assigned to the `zoned` variable.  That means that the next line calling `strftime()` will error out since the variable hasn't been assigned.  See [here](https://github.com/oasis-open/cti-python-stix2/blob/41f2ceb8e55af5a6c378fcd803eef607ee2093ed/stix2/utils.py#L30).

**Comment by clenk** [comment]
Thank you for pointing this out, @chisholm!
