### ISSUE TITLE
Unsupported operand type(s) for Filterset and list

### ISSUE THREAD

**Issue by Voronsky** [oasis-open/cti-python-stix2#173]
Greetings guys!

 Ran into a new issue in particular with the "Filter" feature. IIRC, this was not an issue back in 0.5.1 of Stix2, but since upgrading to 1.0.0 , I've run into this stump when using Filter. So just running the documentation code [here](http://stix2.readthedocs.io/en/latest/guide/taxii.html) ,

 I ran the following
```python3
from stix2 import TAXIICollectionSource
from taxii2client import Collection

# establish TAXII2 Collection instance
collection = Collection("http://127.0.0.1:5000/trustgroup1/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116/", user="admin", password="Password0")
# supply the TAXII2 collection to TAXIICollection
tc_source = TAXIICollectionSource(collection)

filter = Filter("type","=","Indicator")
results = tc_source.query(filter)
```

and immeditately on that results line, I get a stack trace that ends with this
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/stix2/datastore/taxii.py", line 235, in query
    all_data = list(apply_common_filters(all_data, (query - taxii_filters)))
TypeError: unsupported operand type(s) for -: 'FilterSet' and 'list'
```

Has anyone run into this issue? This error also happens if you ran a filter that was written as such
```python3
Filter("type","=","malware")
```

**Comment by emmanvg** [comment]
Hi @Voronsky! Thanks for the submission. Fortunately we have identified this issue in this PR #170 and will be available on the next release. If you are cloning from the repo, I would suggest updating from remote.

**Comment by emmanvg** [comment]
The fix can be found here: https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/datastore/taxii.py#L234-L236. I think we can close this issue, but thanks for reporting!

**Comment by Voronsky** [comment]
Awesome thanks for the response @emmanvg  !
