### ISSUE TITLE
TAXII Data Source should raise an error on 404

### ISSUE THREAD

**Issue by johnwunder** [oasis-open/cti-python-stix2#174]
The following code returns no results, with no error:

```python
from stix2 import TAXIICollectionSource
from taxii2client import Collection

collection = TAXIICollectionSource(Collection("https://ubertaxii.com/taxii/api-root/collections/no-collection-exists/"))

len(collection.query()) # == 0
```

I believe in that case it's an unauthorized error, but this also happens with a 404 and probably some other errors.

It seems like there should be an error raised when a request is made that results in some non-success status from the server, vs. just returning zero results.

**Comment by gtback** [comment]
Related to #113
