### ISSUE TITLE
Add documentation for _valid_refs

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-python-stix2#175]
We need to give an example of how to use `_valid_refs`.

We should also think about letting users just pass a python-stix2 observable object to the constructor of the object that needs the list of valid refs and having it populate it automatically. In other words so you could do

```python
c = NetworkTraffic(src_ref=a, dst_ref=b, protocols='tcp')
```

instead of

```python
c = NetworkTraffic(_valid_refs={"0": "ipv4-addr", "1": "ipv4-addr"}, src_ref="0", dst_ref="1", protocols='tcp')
```

We'll also need to look at what happens when you then add those observables to an ObservedData object.

**Comment by gtback** [comment]
The biggest problem with the current approach is that those strings `"0"` and `"1"` have no meaning outside an ObservedData object. If you start reusing Observables in multiple ObservedData, things can quickly become inconsistant. I'd like for any solution to this problem to address that

**Comment by chisholm** [comment]
I had a similar problem with my workbench/workflow experiments.  I wanted to create network-traffic observables from apache httpd logs.  Just the observables, not the SDOs.  I wanted SDO construction to be a "downstream" operation: they would be built up from a stream of observables.  Problem is, those observables have references, and I needed a way to generate them without having any IDs from an SDO.

What I did was allow the observables to *directly* refer to other observables, which meant there was no need for an ID.  IDs are an indirection mechanism (obs1 -> ID -> obs2); I just cut out the middleman.  So what I wound up with was essentially object graphs composed of observables.  When creating an observed-data SDO, you can slice up the graph along the ref/refs properties to recover the individual observables.  IDs are generated on the fly as needed.  Users never have to deal with them, and they can never be wrong.

Obviously, I was not working with python-stix2 for the graphs and their slicing and dicing.  It was plain dicts.  I had another workflow component that would transform a stream of dicts to a stream of objects by calling stix2.parse() on them all.

Maybe I went off the rails here, but perhaps it will yield some ideas. :)
