### ISSUE TITLE
Custom STIX objects with nested dictionary error

### ISSUE THREAD

**Issue by LiamSennitt** [oasis-open/cti-python-stix2#184]
A custom STIX object with a nested dictionary created using the following example:

``` python
#!/usr/bin/env python3.6

from stix2 import CustomObject, properties

@CustomObject('x-example', [
    ('dictionary', properties.DictionaryProperty()),
])
class Example(object):
    def __init__(self, **kwargs):
        pass

example = Example(dictionary={'key':{'key_one':'value', 'key_two':'value'}})

print(example)
```

throws the following error when calling the `__str__()` method:

``` bash
Traceback (most recent call last):
  File "./example.py", line 16, in <module>
    print(example)
  File "/home/lib64/python3.6/site-packages/stix2/base.py", line 199, in __str__
    return self.serialize(pretty=True)
  File "/home/lib64/python3.6/site-packages/stix2/base.py", line 262, in serialize
    return json.dumps(self, cls=STIXJSONEncoder, **kwargs)
  File "/home/lib64/python3.6/site-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "home/lib64/python3.6/site-packages/simplejson/encoder.py", line 298, in encode
    chunks = list(chunks)
  File "/home/lib64/python3.6/site-packages/simplejson/encoder.py", line 717, in _iterencode
    for chunk in _iterencode(o, _current_indent_level):
  File "home/lib64/python3.6/site-packages/simplejson/encoder.py", line 696, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "home/lib64/python3.6/site-packages/simplejson/encoder.py", line 652, in _iterencode_dict
    for chunk in chunks:
  File "/home/lib64/python3.6/site-packages/simplejson/encoder.py", line 652, in _iterencode_dict
    for chunk in chunks:
  File "/home/lib64/python3.6/site-packages/simplejson/encoder.py", line 602, in _iterencode_dict
    items.sort(key=_item_sort_key)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

the work around is to call:

``` python
print(example.serialize(pretty=False))
```

I'm assuming its something do with how `simplejson` is trying to sort the keys and struggles with the nested dictionary. Is there a reason why the `__str__()` method defaults to `pretty=True`?

**Comment by LiamSennitt** [comment]
Actually looks like the `find_property_index()` method in `utils.py` is returning a `None` type?

**Comment by LiamSennitt** [comment]
Made a pull request which fixes the issue, but thinking about it this could be intentional behaviour. Something like the following might make sense:

``` python
#!/usr/bin/env python3.6

from stix2 import CustomObject, properties

@CustomObject('x-nested', [
    ('key_one', properties.StringProperty()),
    ('key_two', properties.StringProperty()),
])
class Nested(object):
    def __init__(self, **kwargs):
        pass

@CustomObject('x-example', [
    ('dictionary', Nested),
])
class Example(object):
    def __init__(self, **kwargs):
        pass

nested = Nested(key_one='value', key_two='value')

example = Example(dictionary=nested)

print(example)
```

although this throws another error:

``` bash
Traceback (most recent call last):
  File "./example_nested.py", line 23, in <module>
    example = Example(dictionary=nested)
  File "/home/python3.6/site-packages/stix2/v20/sdo.py", line 402, in __init__
    _STIXBase.__init__(self, **kwargs)
  File "/home/lib64/python3.6/site-packages/stix2/base.py", line 154, in __init__
    required_properties = set(get_required_properties(self._properties))
  File "/home/lib64/python3.6/site-packages/stix2/base.py", line 63, in <genexpr>
    return (k for k, v in properties.items() if v.required)
AttributeError: type object '_Custom' has no attribute 'required'
```

**Comment by gtback** [comment]
Thanks, @LiamSennitt . I'll need to look at your PR in a bit more detail, and remember exactly how the custom objects/properties interact with the key sorting behavior. I don't think we want to use the solution in your most recent post, since that would require nesting one STIX Object inside another, which is not supported anywhere else in the specifications. Typically a relationship would be used for this.

**Comment by LiamSennitt** [comment]
Okay great. Yes I wasn't sure if nesting STIX objects would work, I thought it might be similar to the way the `kill_chain_phases` attribute of the `AttackPattern` object has a list of `KillChainPhase` objects? It wouldn't really make sense for there to be a relationship in what I'm trying to do as its a property of the object, so the first example is probably correct.

**Comment by rpiazza** [comment]
IN STIX 2.0 there are top-level objects, which should only be related via a Relationship object or via their id in an embedded relationship (e.g., created_by_ref).  Kill Chain Phases are not a top-level object, which is why they are embedded objects.  Also, if you notice, they don't have an id.

**Comment by LiamSennitt** [comment]
@rpiazza That makes complete sense, thanks you for clarifying. Ignore the second example then, the first one with the nested dictionary is what I want to be able to do.
