### ISSUE TITLE
Property Name Discrepancies in Stix2 Cyber Observable Extensions

### ISSUE THREAD

**Issue by tigerkatz** [oasis-open/cti-python-stix2#194]
I recently noticed the following discrepancies between the property names in Python and the Official Stix documentation for a few [Cyber Observable Extensions.](https://docs.oasis-open.org/cti/stix/v2.0/stix-v2.0-part4-cyber-observable-objects.html)
The discrepancies I have found are as follows.

1. Python stix2.RasterImageExt has property "image_weight" but the documentation specifies "image_width". [Link to doc here.](http://docs.oasis-open.org/cti/stix/v2.0/cs01/part4-cyber-observable-objects/stix-v2.0-cs01-part4-cyber-observable-objects.html#_Toc496716243)

2. Python stix2.WindowsPEBinaryExt Optional Header Type has properties "major_os_version" and "minor_os_version" but the documentation specifies "major_os_system_version" and "minor_os_system_version." [Link to doc here.](http://docs.oasis-open.org/cti/stix/v2.0/cs01/part4-cyber-observable-objects/stix-v2.0-cs01-part4-cyber-observable-objects.html#_Toc496716244)

Thank you

Josh

**Comment by gtback** [comment]
Thanks for reporting this, @tigerkatz . We'll look into fixing this.

**Comment by gtback** [comment]
The first item (`RasterImageExt.image_weight`) is definitely a problem. It's not used in any of the examples, so it wasn't caught by any tests.

The second item looks like a discrepancy in the specification between the Property table (which uses `major_os_version`) and the example (which uses `major_os_system_version`). It looks like the former is what was intended, and [version 2.1](https://docs.google.com/document/d/1epBSNorAYmBVfFnIKNgDzPSXLapL13Jmsmw-WsVfUoY/edit#heading=h.gg5zibddf9bs) uses `major_os_version` in both places, so I don't think this one needs to be changed. Do you agree, @tigerkatz ?

**Comment by rpiazza** [comment]
@tigerkatz: Greg was right - this was an error that I caught, and it was corrected for 2.1.  Unfortunately, at this point, I think we are unable to change the standards document for 2.0.  I'm not sure how how OASIS handles errata.
