### ISSUE TITLE
Is it possible to find observed_data containing certain objects using filter?

### ISSUE THREAD

**Issue by KimSangpil** [oasis-open/cti-python-stix2#200]
Hello.
I want to find observed_data contains ipv4-addr objects with value "1.1.1.1".

        {
            "type": "observed-data",
            "id": "observed-data--bd0b4ea1-b608-4ce5-a6b0-81a3feec5fe6",
            "created": "2018-06-27T01:09:00.749Z",
            "modified": "2018-06-27T01:09:00.749Z",
            "first_observed": "2018-06-27T01:09:00.748465Z",
            "last_observed": "2018-06-27T01:09:00.748472Z",
            "number_observed": 1,
            "objects": {
                "0": {
                    "type": "ipv4-addr",
                    "value": "1.1.1.1"
                },
                "1": {
                    "type": "ipv4-addr",
                    "value": "2.2.2.2"
                },
                "2": {
                    "type": "network-traffic",
                    "src_ref": "0",
                    "dst_ref": "1",
                    "src_port": 13513,
                    "dst_port": 80,
                    "protocols": [
                        "tcp"
                    ]
                }
            }

So I created query containing sub queries. like this

    fs = FileSystemStore("test_data/stix2_store")

    query = [Filter("type", "=", "observed-data")]
    query.append(Filter("objects", "in", "0"))
    query.append(Filter("type", "=", "ipv4-addr"))
    query.append(Filter("value", "=", "1.1.1.1"))
    object_find = fs.query(query)

But it won't work. 
Is there any way to find observed-data containg certain object??

**Comment by clenk** [comment]
Hi @KimSangpil, thank you for your question. Currently you can do something like the following, if that was the only object in the observed-data:

`query = [Filter("objects", "=", {"0": {"type": "ipv4-addr", "value": "1.1.1.1"}})]`

I've created a [Pull Request](https://github.com/oasis-open/cti-python-stix2/pull/203) to add the functionality you're looking for, but in the meantime you may want to look at the [pattern matcher](https://github.com/oasis-open/cti-pattern-matcher), which determines if an observable matches a STIX pattern.

**Comment by gtback** [comment]
Thanks, @KimSangpil . I just merged @clenk's merge request. As he said, you can also use the pattern matcher to look for observables that may contain more just the property you're looking for. At this point, we're unlikely to add much more complexity to filters ("contains" made a lot of sense) because at that point we're basically re-implementing the STIX patterning language.
