### ISSUE TITLE
adding STIX2 Bundle to MemorySource

### ISSUE THREAD

**Issue by mbastian1135** [oasis-open/cti-python-stix2#202]
https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/datastore/memory.py#L36

Cant remember what I (or we) initially thought about adding a STIX2 Bundle to MemorySource but after using API, I expected the MemorySource to read in the parsed JSON STIX2 bundle and have access to the objects. Instead it just had access to the bundle object for querying.  Also - we grab the objects out of a bundle if it is a dict bundle, but not if it is a python-stix2 bundle - which seems incongruous.

**Comment by gtback** [comment]
Could probably combine those first two `if` clauses into just `if isinstance(stix_data, collections.abc.Mapping):` or `if isinstance(stix_data, (_STIXBase, dict)):`

[docs for `collections.abc.Mapping`](https://docs.python.org/3.6/library/collections.abc.html#collections.abc.Mapping), which [`_STIXBase` subclasses](https://github.com/oasis-open/cti-python-stix2/blob/0f5d35f82d7d4bf05414550ac878180f78cdd1b5/stix2/base.py#L66).

**Comment by gtback** [comment]
I'm putting this in the STIX 2.1 milestone for now. If we want to release it in the 1.0.x branch, we can cherry-pick the necessary part of @emmanvg's commit.
