### ISSUE TITLE
The instance of MarkingDefinition cannot pass validation because the 'created' property does't have millisecond.

### ISSUE THREAD

**Issue by win911** [oasis-open/cti-python-stix2#215]
Here is the screenshot:
![marking](https://user-images.githubusercontent.com/5939857/47416920-56c50f00-d7a9-11e8-87a7-aa9b1f82cdb7.PNG)

Source code:
![marking_class](https://user-images.githubusercontent.com/5939857/47417251-2af65900-d7aa-11e8-8914-5b1f0312bbb3.PNG)

Does the 'created' property should be
![property](https://user-images.githubusercontent.com/5939857/47417384-73ae1200-d7aa-11e8-86b3-7960130ca96f.PNG)
to pass validation?

**Comment by clenk** [comment]
Hi @win911! Marking definitions don't have the same requirement as other objects for created to have millisecond precision. However, when using a marking definition defined in the spec, like TLP, the instance defined in the spec must be used. And the TLP Amber instance defined in the spec does have it precise to the millisecond. The validator is ensuring that it matches the spec instance exactly.

If it wasn't a TLP marking, not having the millisecond would be fine.

**Comment by win911** [comment]
Hi @clenk , thanks to your explanation. But how to generate the correct TLP instance defined in the spec? I try to use stix2.TLP_AMBER, but it doesn't have millisecond for created. My objective is to use stix2 module to generate a JSON file which can pass the validation of stix2-validator.

**Comment by clenk** [comment]
This is a bug in python-stix2 - thanks for finding it! We'll get it fixed soon.
