### ISSUE TITLE
TAXIICollection API Filter Multiple results

### ISSUE THREAD

**Issue by Cyb3rWard0g** [oasis-open/cti-python-stix2#217]
Good afternoon,

I was wondering if there was a way to make FILTER return more than one result when a query is provided. For example, I am trying to do the following:

```
ATTCK_STIX_COLLECTIONS = "https://cti-taxii.mitre.org/stix/collections/"
ENTERPRISE_ATTCK = "95ecc380-afe9-11e4-9b6c-751b66dd541e"
ENTERPRISE_COLLECTION = Collection(ATTCK_STIX_COLLECTIONS + ENTERPRISE_ATTCK + "/")
TC_ENTERPRISE_SOURCE = TAXIICollectionSource(ENTERPRISE_COLLECTION)

 filter_objects = [
   Filter('type', '=', 'attack-pattern'),
   Filter('x_mitre_data_sources', '=', 'Packet capture')
]
enterprise_results = TC_ENTERPRISE_SOURCE.query(filter_objects)
print(enterprise_results)
```
I only get the first result back. There are at least 10 things ('attack-pattern') that have that data source in the values of 'x_mitre_data_sources'
I tested it in another way by getting all the 'attack-pattern' values first and then just doing a FOR loop in the results and checking what 'attack-pattern's had from a 'x_mitre_data_sources' perspective and got more than one result. I remember reading once that FILTER only returns one result and cannot iterate over all the results. Is this true? I cant find where I read that. Thank you in advance for your time.

**Comment by chisholm** [comment]
`x_mitre_data_sources` seems to be list-valued.  Try the filter:

`Filter('x_mitre_data_sources', 'contains', 'Packet capture')`

instead.  I.e. replace "=" with "contains".  Does that help?

**Comment by chisholm** [comment]
Ohh, I just noticed that the "=" operator is fudged to mean the same as "contains" when the property value is a list.  Sorry, I missed that.

So, I get:

```
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from stix2.datastore.taxii import *
>>> from taxii2client import *
>>> ATTCK_STIX_COLLECTIONS = "https://cti-taxii.mitre.org/stix/collections/"
>>> ENTERPRISE_ATTCK = "95ecc380-afe9-11e4-9b6c-751b66dd541e"
>>> ENTERPRISE_COLLECTION = Collection(ATTCK_STIX_COLLECTIONS + ENTERPRISE_ATTCK + "/")
>>> TC_ENTERPRISE_SOURCE = TAXIICollectionSource(ENTERPRISE_COLLECTION)
>>>
>>> filter_objects = [
...    Filter('type', '=', 'attack-pattern'),
...    Filter('x_mitre_data_sources', '=', 'Packet capture')
... ]
>>> enterprise_results = TC_ENTERPRISE_SOURCE.query(filter_objects)
>>> print(len(enterprise_results))
32
```

It seems to work, for me (I get 32 results, instead of 1).  My versions:

```
>>> import stix2.version
>>> print stix2.version.__version__
1.0.2
>>> import taxii2client
>>> print taxii2client.__version__
0.3.1
```

@clenk , any ideas?

**Comment by Cyb3rWard0g** [comment]
let me try that 👍

**Comment by Cyb3rWard0g** [comment]
@chisholm thank you very much. I am sorry I was handling the results a little different and I was returning one results ( a dictionary). However, do you know a way to do this case insensitive?? meaning if my query is with "packet capture" instead of "Packet capture" I get 0 results and It is because the value available is "Packet capture". Is there a way to make "FILTER" case insensitive?? . Thank you again @chisholm for taking the time

**Comment by chisholm** [comment]
Looks to me like there is no case-insensitive equals Filter operator.  You'd have to leave the filter off in the taxii query, and then filter the results yourself.

**Comment by Cyb3rWard0g** [comment]
Thank you @chisholm . Thats what I am doing already so now I am sure it needs to be done that way 👍 Thank you again. Have a great weekend!
