### ISSUE TITLE
Can't add custom observables to Observed Data object

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-python-stix2#23]

**Comment by AdamTheAnalyst** [comment]
+1 to this issue - We are doing this by dumping to JSON, adding our properties in, and re-wrapping as ObservedData

**Comment by AdamTheAnalyst** [comment]
Just to add to this - you currently cant have a custom observable in ObservedData - working on a patch.

**Comment by AdamTheAnalyst** [comment]
`import json
from stix2 import bundle
from stix2 import ObservedData
# Custom STIX Observables
@stix2.observables.CustomObservable(type='x-location', properties={
    'country': stix2.properties.StringProperty(required=True),
    'city': stix2.properties.StringProperty(),
})
class CustomLocation():
	def __init__(self, **kwargs):
		pass

location = CustomLocation(country="England",city="Birmingham")

obsd = ObservedData(first_observed=timezone.now(),last_observed=timezone.now(), number_observed=1,objects={
					"0":json.loads(str(location))
					},allow_custom=True)`

**Comment by clenk** [comment]
Thank you for the feedback, @AdamTheAnalyst! I've renamed this issue since the bug you found is unrelated to the original issue, and made [a new issue](https://github.com/oasis-open/cti-python-stix2/issues/31) for the original feature this one was referring to.

I'm also looking into your error and adding a unit test for it.
