### ISSUE TITLE
Ignore empty values for optional fields

### ISSUE THREAD

**Issue by traut** [oasis-open/cti-python-stix2#248]
Latest version of the library will not allow me to create instances of STIX2 classes with `None` or `[]` values for optional fields.

Example:
```python
In [4]: stix2.Malware(name='test malware', labels=['foo', 'bar'], external_references=[])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.p/lib/python3.7/site-packages/stix2/base.py in _check_property(self, prop_name, prop, kwargs)
     89             try:
---> 90                 kwargs[prop_name] = prop.clean(kwargs[prop_name])
     91             except ValueError as exc:

~/.p/lib/python3.7/site-packages/stix2/properties.py in clean(self, value)
    164         if len(result) < 1:
--> 165             raise ValueError("must not be empty.")
    166

ValueError: must not be empty.
```

This forces me to write code like this:
```python
external_references = get_external_references()
if external_references:
    obj = stix2.Malware(
        name='test malware',
        labels=['foo', 'bar'],
        external_references=external_references)
else:
    obj = stix2.Malware(
        name='test malware',
        labels=['foo', 'bar'])
```
which is inconvenient.

Proposed solution: the library should accept empty fields for optional fields but should not serialize these in the output JSON, treating these fields as unset

**Comment by rpiazza** [comment]
Hi @traut,

Yes, this is quirk in the specification. Here is the relevant clause:

Empty lists are prohibited in STIX and MUST NOT be used as a substitute for omitting the property if it is optional. If the property is required, the list MUST be present and MUST have at least one value.

As far as handling this in python-stix2, just omit the keyword argument.

**Comment by traut** [comment]
@rpiazza of course, hence my comment on skipping the fields with empty values during serialisation. I see no reason enforsing STIX2 spec on _python objects_, since enforcing it during serialisation would be enough

**Comment by rpiazza** [comment]
I agree that needing to check for empty values is annoying.  Not being a python guru - I wonder if there is a way to make this code more compact.

**Comment by traut** [comment]
In my opinion, the library can perfectly cope with empty values, ignoring them for optional fields, which will make using it much easier

**Comment by chisholm** [comment]
`malware["external_references"].append("foo")` would constitute a modification (without bumping `modified`), right?  As you said, the position taken in the API design is that that's a spec violation.  I don't think it makes sense to worry about expectations regarding an operation that shouldn't even be allowed.  I think the old python-stix library has an immutable list type that it uses to prevent this kind of "behind-your-back" modification.  We don't have that enforcement, but surely it's still something we'd think of as illegal, right?  So I don't think that's a legitimate worry.  I think we should be okay with dropping the property.

**Comment by chisholm** [comment]
Here's a code style idea, fwiw.  Dump everything into a dict, None's, empty lists, etc and all.  Then just filter out the empty stuff in a post-processing pass.  E.g.

```python
cleaned = {k:v for k,v in your_dict.items() if v}
obj = Malware(**cleaned)
```

That is actually a little too aggressive: it would filter out properties with value 0, so you probably want to check specifically for None or an empty list.  Something like that.  That could be put into its own function and reused.  Also, if your dicts have a "type" property, you don't need to hard-code classes, just use `stix2.parse()`.  A generic bit of code might look like:

```python
def make_object():
    obj_dict = build_obj_dict()  # however you get your property information
    obj = stix2.parse(clean_props(obj_dict))  # clean_props() contains the "cleaning" code from above
    return obj
```

If you know everything's correct in your dict, then maybe you don't need to involve stix2.  Maybe one advantage might be a simple validation check: ensure property names aren't misspelled, required properties aren't missing, etc?

And yeah, the stix2 library could be doing this automatically.

**Comment by clenk** [comment]
True. I'd be okay with a PR that drops empty lists for optional properties. The code here is probably what would need to be changed: https://github.com/oasis-open/cti-python-stix2/blob/f09960d7ff0a357d0e5d6c3c1c10b826577ec850/stix2/base.py#L150
