### ISSUE TITLE
TLP MarkingDefinition does not use identifiers required by STIX2 spec

### ISSUE THREAD

**Issue by traut** [oasis-open/cti-python-stix2#252]
TLP Marking Definition objects are required to have one of the predefined identifiers for every color - http://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709287

At the moment stix2 library generates random identifier:
```python
In [4]: stix2.MarkingDefinition(definition_type='tlp', definition=stix2.TLPMarking(tlp='red'))
Out[4]: MarkingDefinition(type='marking-definition', id='marking-definition--ff3c4a8a-4aeb-4b51-8400-3d98e0e20055', created='2019-01-29T18:58:31.689Z', definition_type='tlp', definition=TLPMarking(tlp='red'))

In [5]: stix2.MarkingDefinition(definition_type='tlp', definition=stix2.TLPMarking(tlp='red'))
Out[5]: MarkingDefinition(type='marking-definition', id='marking-definition--a0d1fd11-25e3-466b-9338-aabc4868c769', created='2019-01-29T18:58:32.585Z', definition_type='tlp', definition=TLPMarking(tlp='red'))
```

Expected behaviour: when TLP MarkingDefinition is created, one of predefined identifiers must be used.

**Comment by emmanvg** [comment]
@traut, the library has TLP Marking constants that follow the spec requirements. You can access them directly from the top-level import. Example:

``` python
>>> import stix2
>>> print(stix2.TLP_RED)
{
    "type": "marking-definition",
    "id": "marking-definition--5e57c739-391a-4eb3-b6be-7d15ca92d5ed",
    "created": "2017-01-20T00:00:00.000Z",
    "definition_type": "tlp",
    "definition": {
        "tlp": "red"
    }
}
```
Does that help with any trouble you are using?

Also, keep in mind its not only the identifiers, but also the created time must match the instances defined in the spec.

**Comment by traut** [comment]
@emmanvg of course, the values are there, as well as in STIX spec. This ticket is about the library creating incorrect MarkingDefinition objects by default.
