### ISSUE TITLE
How to create Cyber Observable References

### ISSUE THREAD

**Issue by adidier17** [oasis-open/cti-python-stix2#256]
I'm finding a lack of documentation in cti-python-stix2 for creating object references for cyber observables as specified in the [stix2 documentation](http://docs.oasis-open.org/cti/stix/v2.0/cs01/part3-cyber-observable-core/stix-v2.0-cs01-part3-cyber-observable-core.html#_Toc496715374). Specifically, I am trying to create a from_ref in the EmailMessage object:
`from = EmailAddress(value="Annie.K.Didier@jpl.nasa.gov, display_name="Annie")
body = [ {'content_type': 'text/plain',
  'body': "\r\n\r\n\r\nYour package has been delivered.\r\n\r\n \r\n\r\nDelivery Data:  Thursday, 3/7/2019\r\n\r\n \r\n\r\nDelivery Time:  10:44 AM\r\n\r\n\r\n\r\n\r\n\r\n\r\nThis notification is to confirm that the following shipment has been delivered.\r\n\r\n \r\n\r\nTracking Number:  1Q767AZ20351136904\r\n\r\n \r\n\r\n     Visit  us on Facebook            \r\n\r\n     Download  the UPS mobile app\r\n\r\n \r\n\r\n© 2018 United Parcel Service of America, Inc. UPS, the UPS brandmark, and the color brown are trademarks of United Parcel Service of America,  Inc. All rights reserved.\r\n\r\nAll trademarks, trade names, or service marks that appear in connection with UPS's services are the property of their respective owners.\r\n \r\nPlease do not reply directly to this e-mail. UPS will not receive any reply message.\r\nFor more information on UPS's privacy practices, refer to the UPS Privacy Notice.\r\nFor questions or comments, visit Contact UPS.\r\n\r\nThis communication contains proprietary information and may be confidential. If you are not the intended recipient, the reading, copying, disclosure or other use of the contents of this e-mail is strictly prohibited and  you are instructed to please delete this e-mail immediately.\r\n\r\n \r\n\r\nUPS  Privacy Notice\r\n\r\n \r\n\r\nContact  UPS\r\n\r\n\r\n\r\n\r\n\r\n\r\n"},
{'content_type': 'text/html',
  'body': '<html>\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\r\n<style type="text/css" style="display:none;"></style>\r\n</head>\r\n<body dir="ltr">\r\n<div id="divtagdefaultwrapper" dir="ltr" style="font-size:12pt; color:rgb(0,0,0); font-family:Calibri,Helvetica,sans-serif,EmojiFont,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;,NotoColorEmoji,&quot;Segoe UI Symbol&quot;,&quot;Android Emoji&quot;,EmojiSymbols">\r\n<p style="margin-top:0; margin-bottom:0"></p>\r\n<p style="font-size:16px; font-family:Calibri,Helvetica,sans-serif,EmojiFont,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;,NotoColorEmoji,&quot;Segoe UI Symbol&quot;,&quot;Android Emoji&quot;,EmojiSymbols">\r\n<img size="4317" id="img667191" tabindex="0" style="max-width: 99.9%;'}]

email = EmailMessage(is_multipart="true", subject="Subject", body_multipart=body, from_ref=??? what goes here?)

observable = stix_obs = ObservedData(
 
    created="2017-02-28T19:37:11.213Z",
    modified="2017-02-28T19:37:11.213Z",
    first_observed="2017-02-27T21:37:11.213Z",
    last_observed="2017-02-27T21:37:11.213Z",
    number_observed=1,
    objects = {"0": email, "1": from}
`

So how do you create the reference to the from EmailAddress? I've looked at the classes in properties.py and still haven't figured it out.

**Comment by khdesai** [comment]
Currently, there isn't an ideal way for creating references to Cyber Observables. You could define all of the Cyber Observable objects within the `objects` dict in your `ObservedData` object (and then use the number-based reference mechanism mentioned in the current stix2 documentation), but that is obviously not an elegant/practical solution. 

Moving forward, the currently proposed mechanism for handling such references is to use `_valid_refs`, but looking at #175, this is also a work in progress. Although formal documentation is currently lacking for `_valid_refs`, you may be able to gain some insights from stix2/test/v21/test_observed_data.py since some of the tests there use `_valid_refs`.

And, I think in the context of your situation as I've understood it, the `is_multipart` property should be equal to True, not "true".

**Comment by khdesai** [comment]
There is now documentation regarding the use of `_valid_refs` to create references to Cyber Observables. The documentation can be found in [/docs/guide/creating.ipynb](https://github.com/oasis-open/cti-python-stix2/blob/master/docs/guide/creating.ipynb) (towards the end of the file) starting at "Creating Cyber Observable References".

Just remember that `_valid_refs` is only designed to create/handle references to Cyber Observables, and is not officially meant as a mechanism for reference _resolution_, as per the spec.

**Comment by Ksk190809** [comment]
In referencing the documentation cited, [/docs/guide/creating.ipynb](https://github.com/oasis-open/cti-python-stix2/blob/master/docs/guide/creating.ipynb), the case "case 2" style did not work for me in the following example (whereas "case 1" style did):

Code: [email_address_references_py.txt](https://github.com/oasis-open/cti-python-stix2/files/3486754/email_address_references_py.txt)
Output: [email_address_references_output.txt](https://github.com/oasis-open/cti-python-stix2/files/3486795/email_address_references_output.txt)

**Comment by khdesai** [comment]
Thanks for pointing that out; that issue only seems to arise when using python3.x, but not python2.x. (please confirm). We'll look into why that is and get back to you soon. 

If you have any ideas of why this issue only appears with python3 but not python2, please let us know :)

**Comment by clenk** [comment]
Hi @Ksk190809, can you try again with the latest release on PyPI? We had a fix for this on master but had not yet included it in a PyPI release. Thanks!

**Comment by khdesai** [comment]
Just leaving a comment here to let users know that this issue (specifically the use of `_valid_refs`) is mitigated in STIX 2.1 (updates coming very soon to the stix2.1 branch of the code base). This is because the most recent updates to the STIX specs (Working Draft 05) specify that Cyber Observable references should be made using the (new) ID property of whichever Cyber Observable object(s) is being referenced.

**Comment by clenk** [comment]
I believe this has been addressed and am closing the issue due to lack of activity, but if this is still an problem with the latest version feel free to reopen or create an new issue.
