### ISSUE TITLE
Passing a list to Bundle constructor creates list within a list

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-python-stix2#26]
Currently if you pass a list to the Bundle constructor it creates a list within a list: 

```json
        {
          "objects":
             [
               [
                   { },
                   { }
               ]
             ]
        }
```

If the first argument is a list, the constructor should just assign it to `objects`.

**Comment by gtback** [comment]
If someone passes a list and also uses the `objects` kwarg, I think we should append to the list, just like we do for `*args` now.
