### ISSUE TITLE
ExtraPropertiesError: Unexpected properties for Indicator: (a custom propety).

### ISSUE THREAD

**Issue by lorinwu** [oasis-open/cti-python-stix2#265]
I am using new_version api to modify some property value, however, I was told above "ExtraPropertiesError: Unexpected properties for Indicator: (a custom property).", I added a custom property to Indicator SDO, now I can't change it now.

**Comment by khdesai** [comment]
If you look at [stix2/markings/object_markings.py:39](https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/markings/object_markings.py#L39), you'll see that simply appending `allow_custom=True` to the arguments when you call `new_version()` will take care of the error you're getting.

**Comment by clenk** [comment]
As @khdesai said, you can do something like

```python
my_object.new_version(custom_property='something', allow_custom=True)
```

If this doesn't work please feel free to reopen the issue.
