### ISSUE TITLE
Filter on x-mitre-tactic return a dict rather than a Stix CustomObject

### ISSUE THREAD

**Issue by andreamargheri** [oasis-open/cti-python-stix2#270]
Object returned by a filter on the custom SDO `x-mitre-tactic` defined as follows
`tactics = fs.query([Filter('type', '=', 'x-mitre-tactic')])
`
returns a `dict` so that properties must be accessed like `tactics[0]['name']` rather than `tactics[0].name`

**Comment by emmanvg** [comment]
@andreamargheri your issue might be related to mitre/cti#45

**Comment by andreamargheri** [comment]
Yes you are right! 

Registering the CustomObject of the `x-mitre-tactic` as follows
`@CustomObject('x-mitre-tactic', [
    ('x_mitre_shortname', properties.StringProperty(required=True))
])
class Tactic(object):
    def __init__(self, x_mitre_shortname, **kwargs):
        if not x_mitre_shortname:
            raise ValueError("Name of tactic must be provided." % x_mitre_shortname)
`
allows the filter to work properly, as well as to serialise it in a Bundle

**Comment by payamsamimi** [comment]
Unfortunately, I have still this problem. I have already added the custom object to my python recipe, however, I receive the following error:
Invalid value for Bundle 'objects': Can't parse unknown object type 'x-mitre-tactic'! For custom types, use the CustomObject decorator.

**Comment by clenk** [comment]
Thank you for creating a new issue @payamsamimi - we'll address your issue there instead of here.
