### ISSUE TITLE
Some question about bundle relation

### ISSUE THREAD

**Issue by 631068264** [oasis-open/cti-python-stix2#276]
stix2   1.1.2 
py 3.7

if I want to create **relationship** between two object in two different bundle how to do that

**Comment by clenk** [comment]
Hi @631068264, bundles are not permanent objects and don't have any semantic meaning. Usually we work directly with the objects, not the bundles. If your bundle is a variable called `bundle`, you can access its objects with `bundle['objects']` or `bundle.objects`, both of which will give you a list containing those objects. You can then create relationships between those objects by following the examples in the [User's guide documentation](https://stix2.readthedocs.io/en/latest/guide/creating.html#Creating-Relationships).
