### ISSUE TITLE
Location Name Field Missing

### ISSUE THREAD

**Issue by AdamTheAnalyst** [oasis-open/cti-python-stix2#280]
Location was missing the optional name field, causing:

`stix2.exceptions.ExtraPropertiesError: Unexpected properties for Location: (name).`

When running

`Location( name="united kingdom", country="UK" )`

Reference to the working draft where name is specified in the Location field as optional:

https://docs.google.com/document/d/1bkMmU1PxlwlAwjrMmyWV147rvLcRs2x62FicHbpH2gU/edit#

Proposed fix in PR https://github.com/oasis-open/cti-python-stix2/pull/279

Cheers,

Adam

**Comment by khdesai** [comment]
Thanks for the PR! 

As you may already know, the reason for the error is because the code base is currently compliant with Working Draft 04, but the `name` property is new for Working Draft 05. 

We'll be updating the code base soon to be compatible with WD 05.
