### ISSUE TITLE
No error when adding Granular Marking with invalid selector

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-python-stix2#29]
The API should throw an error if a granular marking is added to an object but one of its selectors references a property or list item that is not present on that object. Or if it doesn't throw an error, it should at least omit the invalid selector.

**Comment by emmanvg** [comment]
Hi @clenk, @gtback ! I started an effort to work on this and on a simpler way to apply markings to objects. Though, I never finished and probably won't be able to in a couple of weeks. So, if someone is able to take that step. It would be awesome. I pushed my latest changes on my [fork](https://github.com/emmanvg/cti-python-stix2/tree/marking-support) (which might be outdated). Is currently [WIP], but hopefully will give some ideas on how to raise the error if you or someone else want to tackle this issue.

**Comment by clenk** [comment]
Thanks, @emmanvg! I'll take a look.
