### ISSUE TITLE
Fix custom observable machinery for STIX 2.1

### ISSUE THREAD

**Issue by chisholm** [oasis-open/cti-python-stix2#299]
Although there are different `CustomObservable` decorators for STIX 2.0 and 2.1, they both use the same `_custom_observable_builder()` function to create the custom class.  That function does things which don't make sense for STIX 2.1.  The system needs to be changed/updated to make sense with both STIX versions.

For example, one of the things that function does is to check whether properties named "*_ref(s)" use an instance of `ObjectReferenceProperty`.  That class was specifically written to interact with validation of old-style SCOs, i.e. those embedded in the `objects` property of the 2.0 `observed-data` SDO.  The design of SCOs has had significant changes in STIX 2.1, and the check doesn't make sense with that version of custom observable.

**Comment by clenk** [comment]
This was fixed by #297.
