### ISSUE TITLE
Custom ExternalReference object causes invalid value error

### ISSUE THREAD

**Issue by yukh1402** [oasis-open/cti-python-stix2#308]
**Long story short**
I would like to create an Indicator SDO with multiple customized external references. All external references have the key allow_custom so that customized keys can be set correctly. When the external references list is set in the Indicator SDO an error occurs.

**Expected behaviour**
I expect that the Indicator SDO can use multiple customized external references.

**Actual behaviour**
The ExternalReference object can be build without any issue but after assigning it in the Indicator SDO by setting external_references=[ExternalReference] the following error occurs:

stix2.exceptions.InvalidValueError: Invalid value for Indicator 'external_references': Unexpected properties for ExternalReference: (test_ob).

**Sample code:**

```
external_reference = ExternalReference(source_name='test',
                                           description='tefe',
                                           test_ob='ddd',
                                           allow_custom=True)
print(Indicator(external_references=[external_reference],
                labels=['test'],
                description='test',
                name='test',
                pattern="[url:value = '{}']".format("www.test.com")
))
```

Version:
stix2 1.2.1

**Comment by clenk** [comment]
Hi @yukh1402, thanks for the bug report. We'll get this fixed.

**Comment by yukh1402** [comment]
> Hi @yukh1402, thanks for the bug report. We'll get this fixed.

**Comment by yukh1402** [comment]
Hi @clenk, thank you very much.

**Comment by clenk** [comment]
@yukh1402 we have a fix in master now that will be included in the next release.
