### ISSUE TITLE
'socket-ext' object value checking

### ISSUE THREAD

**Issue by zrush-mitre** [oasis-open/cti-python-stix2#309]
Currently, the socket extension for the networking object is only allowed to match 'SO_\*'. It should match 'ICMP_\*', 'ICMP6_\*', 'IP_\*', 'IPV6_\*', 'MCAST\_*', 'TCP_\*', and 'IRLMP_\*'.

**Comment by rpiazza** [comment]
Related to https://github.com/oasis-open/cti-stix-validator/issues/103
