### ISSUE TITLE
stix2 object uuid doesn't support generation base on NAMESPACE_URL

### ISSUE THREAD

**Issue by acabrol** [oasis-open/cti-python-stix2#313]
a new different uuid is generated event if there if it is an update.

It make issue to change validation period for an indicator and update the object in Threat Intelligence Tools.

could you support uuid5 ? in order to use NAMESPACE_* for a better support of updates?

**Comment by clenk** [comment]
Hi @acabrol, can you give a little more information on how you are updating the indicator? If you use the `new_version()` method (e.g. `my_indicator.new_version(valid_from=my_new_timestamp)`) it should use the same id and not generate a new one.

STIX 2.0 requires uuidv4, but if you are using the STIX 2.1 version of Indicator (`from stix2.v21 import Indicator`) it will let you assign a uuidv5 id to the indicator's id property. For example: 
```python
myid = uuid.uuid5(uuid.NAMESPACE_URL, 'myindicator')
indicator = Indicator(id="indicator--{}".format(str(myid)), ... )
```

**Comment by acabrol** [comment]
Thank you for your answer i will use the STIX 2.1

**Comment by acabrol** [comment]
Using:
```
import stix2.v21 as stix2
generated_uuid=uuid.uuid5(uuid.NAMESPACE_URL,"myurl")
indicator = stix2.Indicator(id="indicator--"+str(generated_uuid))
```
It works Thank you.
