### ISSUE TITLE
new_version() doesn't ensure the new "modified" property is greater than the old one

### ISSUE THREAD

**Issue by chisholm** [oasis-open/cti-python-stix2#329]
https://github.com/oasis-open/cti-python-stix2/blob/88426de4241533915ec7f0286254d28d0b03137d/stix2/utils.py#L287

When creating a new version and the user hasn't specifically assigned a new `modified` property value, the current time is used as the new value.  This isn't guaranteed to be any different from the old one.  A unit test failed because the original and new version objects were created so quickly that their timestamps were the same.

**Comment by clenk** [comment]
Closed by #374.
