### ISSUE TITLE
Bundles don't check objects

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-python-stix2#33]
The Bundle class [doesn't perform any checks](https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/bundle.py#L14) on what is added to its `objects` property.

We need to implement this check from the spec:
> Objects in this list MUST be a STIX Object (SDO, SRO or Custom Object) or a Marking Definition object.

This may mean we need to refactor more code like we did for #23.

**Comment by clenk** [comment]
This was fixed in ee8013d.

**Comment by gtback** [comment]
Lol, I forgot this issue existed when I made #40 ☹️ . Thanks, @clenk
