### ISSUE TITLE
Changes to Malware Analysis object

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-python-stix2#339]
see https://github.com/oasis-tcs/cti-stix2/issues/213 and https://github.com/oasis-tcs/cti-stix2/issues/210

**Comment by clenk** [comment]
* `av_result` - split into result_name and result
* `sample_ref` - new property, identifier (of type file, network-traffic, and artifact)
* common relationships - av-analysis-of renamed to analysis-of

**Comment by clenk** [comment]
This has been addressed in #356 and #357.
