### ISSUE TITLE
README.rst - Creating STIX Domain Objects

### ISSUE THREAD

**Issue by nullouis** [oasis-open/cti-python-stix2#43]
The first example in [https://github.com/oasis-open/cti-python-stix2/blob/master/README.rst](url) does not verify with [https://github.com/oasis-open/cti-pattern-validator/blob/master/README.rst](url)

I suppose the correct example should be this.

indicator = Indicator(name="File hash for malware variant",
                      labels=['malicious-activity'],
                      **pattern="[file:hashes.md5 = 'd41d8cd98f00b204e9800998ecf8427e']"**)

**Comment by clenk** [comment]
Thank you for finding this discrepancy in our documentation, @nullouis! This has been fixed in cd1851c.
