### ISSUE TITLE
Indicators with special characters

### ISSUE THREAD

**Issue by krmaxwell** [oasis-open/cti-python-stix2#432]
While processing an indicator of the form `http://example.com/evil.txt')`, an exception was encountered:
```
Exception has occurred: InvalidValueError
Invalid value for Indicator 'pattern': FAIL: Error found at line 1:50. mismatched input ')' expecting ']'
```

Should users expect to escape these strings themselves (e..g `http://example.com/evil.txt\'\)`), or is that better handled in the module itself?

**Comment by clenk** [comment]
Hi @krmaxwell, strings in STIX patterns in Indicators must be surrounded by apostrophes (`'` U+0027). The STIX specification says in [Section 9.2](https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_bvkuhhujn5qm):

> The escape character is the backslash (`\` U+005c). Only the apostrophe or the backslash may follow, and in that case, the respective character is used for the sequence.

So yes, single quotes within patterns need to be escaped to avoid confusion with the end of the string.

**Comment by krmaxwell** [comment]
Alright, thanks for the clarification!
