### ISSUE TITLE
Many datastores and helpers assume created and modified fields exist in objects

### ISSUE THREAD

**Issue by maybe-sybr** [oasis-open/cti-python-stix2#441]
As an example, `CompositeDataSource`s attempt to access the `modified` key directly as well as making use of the `deduplicate()` helper which attempts to access `modified` and then falls back to `created` if that's missing. The following snippet shows a handful of breakages which present as you squash each one.

```python
import traceback

import pytest
import stix2.datastore
import stix2.datastore.memory
import stix2.v21

m1 = stix2.datastore.memory.MemoryStore()
m2 = stix2.datastore.memory.MemoryStore()
c = stix2.datastore.CompositeDataSource()
c.add_data_sources((m1.source, m2.source))

o = stix2.v21.Software(name="foo")
m1.add(o)
m2.add(o)

with pytest.raises(KeyError) as caught:
    c.get(o.id)
print(caught.getrepr())
```

The table in section 3.2 shows the exceptions, but even that's not reliable since custom properties could be implemented per section 11.1 to implement versioning per section 3.6 (e.g. for SCOs).

This grep line shows all accesses outside the tests, but I suspect only `utils.py`, `versioning.py` and the datastores would need to be changed.
```sh
$ grep -Er "\[[\"'](created|modified|revoked)" stix2/*.py stix2/canonicalization/ stix2/confidence/ stix2/datastore/ stix2/markings/ stix2/v20/ stix2/v21/
...
```

Most of these accesses seem to be related to sorting versions so it seems like it might be reasonable to instead implement a single helper in `versioning.py` which accepts a series of objects, sorts and (optionally?) deduplicates them. I'm happy to work on a patchset for this but wanted to get some input on an approach.

**Comment by chisholm** [comment]
CompositeDataSource and deduplicate() didn't handle unversioned objects correctly.  I made a PR to address that.  The other datastores have already had updates to support them, so they should be okay.  But do report any issues you find!

As far as `versioning.py`, I think some functions in there could be improved.  New issues should be created though, about more specific problems with specific areas of the code.  We will create new issues as they are addressed.

**Comment by maybe-sybr** [comment]
Excellent, thanks for putting #444 up, @chisholm - looks like it'll do nicely :)
