### ISSUE TITLE
PyInstaller - Key Error: 'v21' in _detect_spec_version

### ISSUE THREAD

**Issue by stianvale** [oasis-open/cti-python-stix2#446]
Hi! 
I'm building a python executable that utilizes stix2 and taxii2client to fetch MITRE ATT&CK Enterprise data. 
When I'm running the python script everything works, but after building the executable, I'm getting a Key Error in the method _detect_spec_version. 

Is there some way to specify the stix version when calling the taxii datastore, so that I can mitigate this error? 

Minimum code example:
```
from stix2 import TAXIICollectionSource, Filter
from taxii2client.v20 import Server, Collection

collection = Collection("https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/")
tc_source = TAXIICollectionSource(collection)

filter = Filter("type", "=", "attack-pattern")
techniques = tc_source.query(filter)
```

Traceback: 
```
  File "stix2\datastore\taxii.py", line 309, in query
  File "stix2\datastore\taxii.py", line 309, in <listcomp>
  File "stix2\parsing.py", line 47, in parse
  File "stix2\parsing.py", line 129, in dict_to_stix2
  File "stix2\parsing.py", line 82, in _detect_spec_version
KeyError: 'v21'
```

**Comment by emmanvg** [comment]
I am not familiar with PyInstaller therefore my help there is limited. For the DataStore API there is a way to provide a static version like so:

``` python
from stix2 import TAXIICollectionSource, Filter
from taxii2client.v20 import Server, Collection

collection = Collection("https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/")
tc_source = TAXIICollectionSource(collection)

filter = Filter("type", "=", "attack-pattern")
techniques = tc_source.query([filter], version="v2.0")
```

Let me know if this helps.

**Comment by stianvale** [comment]
Thanks @emmanvg ! 

That got me one step further, although now I'm getting a key error in parsing.py

Traceback: 
```
  File "stix2\datastore\taxii.py", line 309, in query
  File "stix2\datastore\taxii.py", line 309, in <listcomp>
  File "stix2\parsing.py", line 47, in parse
  File "stix2\parsing.py", line 131, in dict_to_stix2
KeyError: 'v20'
```

Do you know how to fix this?

**Comment by emmanvg** [comment]
It might be a problem with PyInstaller, but it seems this [global variable](https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/parsing.py#L14) is not populated when you reach line `131` in the traceback you provided. Not sure if you would need a hook for it.

Normally that global variable is populated via a call to this [method](https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/parsing.py#L389) and that happens [here](https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/__init__.py#L63).

**Comment by stianvale** [comment]
Okey thanks, I'll close the issue and investigate some more:)
