### ISSUE TITLE
error creating bundle

### ISSUE THREAD

**Issue by stbones** [oasis-open/cti-python-stix2#447]
I have a indicator object and a list (contains list of Notes). when I try to create bundle of them, i get below error. 
However, when I just pass the list that contains Notes, it works fine. 

**Error**
InvalidValueError: Invalid value for Bundle 'objects': This property may only contain a dictionary or object

**code:**
import datetime
from stix2 import Note, Bundle, Indicator
mem = stix2.MemoryStore()
datetime = datetime.datetime.today().strftime('%Y-%m-%d-%H:%M:%S')

ind1 = Indicator(
    indicator_types=['malicious-activity'],
    pattern_type="stix",
    pattern="[file:hashes.MD5 = 'd41d8cd98f00b204e9800998ecf8427e']",
    valid_from="2017-01-01T12:34:56Z",
)

Note_list = [Note(type='note', spec_version='2.1', id='note--830ca0aa-75b7-4526-865c-b4f9ded77735', created_by_ref='identity--f431f809-377b-45e0-aa1c-6a4751cae5ff', created='2020-08-21T20:18:48.839396Z', modified='2020-08-21T20:18:48.839396Z', abstract='Cyber Bulletin Comment 1', content='Issue 1', object_refs=['report--84e4d88f-44ea-4bcd-bbf3-b2c1c320bcb3'], object_marking_refs=['marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9']), Note(type='note', spec_version='2.1', id='note--f2362c5a-5c06-40a1-a678-db875dbee714', created_by_ref='identity--f431f809-377b-45e0-aa1c-6a4751cae5ff', created='2020-08-21T20:18:48.840376Z', modified='2020-08-21T20:18:48.840376Z', abstract='Comment 2', content='Issue 2', object_refs=['report--84e4d88f-44ea-4bcd-bbf3-b2c1c320bcb3'], object_marking_refs=['marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9']), Note(type='note', spec_version='2.1', id='note--72fe7b65-4055-424f-b201-99e8dde86f86', created_by_ref='identity--f431f809-377b-45e0-aa1c-6a4751cae5ff', created='2020-08-21T20:18:48.840538Z', modified='2020-08-21T20:18:48.840538Z', abstract='Cyber Bulletin Comment 3', content="Issue 3", object_refs=['report--84e4d88f-44ea-4bcd-bbf3-b2c1c320bcb3'], object_marking_refs=['marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9'])]

bundle = Bundle([ind1 , Note_list])

print (bundle)

**Comment by clenk** [comment]
Hi @stbones. The Bundle constructor is expecting to get a single list with all the objects. `[ind1 , Note_list]` puts the Notes in a list inside the list. The following should work, as it will concatenate the two strings instead:

```python
bundle = Bundle([ind1] + Note_list)
```

Let us know if that doesn't work or you have further questions!

**Comment by stbones** [comment]
thank you it worked out. 

> Hi @stbones. The Bundle constructor is expecting to get a single list with all the objects. `[ind1 , Note_list]` puts the Notes in a list inside the list. The following should work, as it will concatenate the two strings instead:
> 
> ```python
> bundle = Bundle([ind1] + Note_list)
> ```
> 
> Let us know if that doesn't work or you have further questions!
