### ISSUE TITLE
Issue while exporting list of bundle

### ISSUE THREAD

**Issue by stbones** [oasis-open/cti-python-stix2#448]
HI 

I have list of bundles stored in a Python List, and i want to export it to json file. But when I use stix2 memorystore it **clubs** all the bundles into one big bundle, that is not i want, i want a separate bundle. any help?

### **Here is my snip it of my code:**

bundle_list = []
def create_bundle(list):
    for item in list:
        mark = stix2.MarkingDefinition(
            id=item['marking_definition_uuid'],
            created="2017-01-20T00:00:00.000Z",
            definition_type="tlp",
            name="TLP:" + item["TLPLevel"],
            definition={"tlp": item["TLPLevel"].lower()}
        )
        id_ind = stix2.Identity(
            id=item['individual_uuid'],
            created_by_ref="identity--a463ffb3-1bd9-4d94-b02d-74e4f1658283",
            object_marking_refs=item['marking_definition_uuid'],
            identity_class="individual",
            name=item['PostingPortalUserName'],
            description="item Author",
            sectors='energy',
            contact_information=item['PostingPortalUserEmail']
        )
        bundle = stix2.Bundle(mark, id_ind)
        bundle_list.append(bundle)
mem.add([bundle_list])
mem.save_to_file("/home/sampleFile/testNote112/.json")

**### It produces below output from bundle_list list:**
[Bundle(type='bundle', id='bundle--0b9750f5-019d-4d47-944c-b600cff3056d', objects=[MarkingDefinition(type='marking-definition', spec_version='2.1', id='marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9', created='2017-01-20T00:00:00.000Z', definition_type='tlp', name='TLP:White', definition=TLPMarking(tlp='white')), Identity(type='identity', spec_version='2.1', id='identity--fe848b48-d10e-11ea-a8cf-005056b2ddba', created_by_ref='identity--a463ffb3-1bd9-4d94-b02d-74e4f1658283', created='2020-08-24T20:41:27.189598Z', modified='2020-08-24T20:41:27.189598Z', name=' ', description='Author', identity_class='individual', sectors=['corp'], object_marking_refs=['marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9'])]), Bundle(type='bundle', id='bundle--1fb24c65-7f7e-44d4-b694-ff06c1bcc406', objects=[MarkingDefinition(type='marking-definition', spec_version='2.1', id='marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9', created='2017-01-20T00:00:00.000Z', definition_type='tlp', name='TLP:White', definition=TLPMarking(tlp='white')), Identity(type='identity', spec_version='2.1', id='identity--fe848b48-d10e-11ea-a8cf-005056b2ddba', created_by_ref='identity--a463ffb3-1bd9-4d94-b02d-74e4f1658283', created='2020-08-24T20:41:27.190664Z', modified='2020-08-24T20:41:27.190664Z', name=' ', description='Author', identity_class='individual', sectors=['corp'], object_marking_refs=['marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9'])]), Bundle(type='bundle', id='bundle--e88eaac7-864b-4339-8102-6bbe5e3d6628', objects=[MarkingDefinition(type='marking-definition', spec_version='2.1', id='marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9', created='2017-01-20T00:00:00.000Z', definition_type='tlp', name='TLP:White', definition=TLPMarking(tlp='white')), Identity(type='identity', spec_version='2.1', id='identity--fe848b48-d10e-11ea-a8cf-005056b2ddba', created_by_ref='identity--a463ffb3-1bd9-4d94-b02d-74e4f1658283', created='2020-08-24T20:41:27.191614Z', modified='2020-08-24T20:41:27.191614Z', name=' ', description='Author', identity_class='individual', sectors=['corp'], object_marking_refs=['marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9'])])]

**Comment by clenk** [comment]
The [STIX specification](https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_gms872kuzdmg) says that a "Bundle does not have any semantic meaning and the objects contained within the Bundle are not considered related by virtue of being in the same Bundle" and that a "Bundle is transient, and implementations SHOULD NOT assume that other implementations will treat it as a persistent object or keep any custom properties found on the bundle itself." The memory store is merging them all into one bundle because bundles don't mean anything in STIX.

If you need to keep them separate you could use separate memory stores or use the Grouping object to group the objects together inside the same memory store. If you were storing the objects in a TAXII datastore you could put them in different collections. Hope this helps!

**Comment by stbones** [comment]
thank you
