### ISSUE TITLE
Cannot create a CustomObject that contains a List of the same type CustomObject

### ISSUE THREAD

**Issue by asdimitriadis** [oasis-open/cti-python-stix2#457]
The issue is that I cannot create a CustomObject (e.g., ObjectA) that contains a list of the same object type (i.e., ObjectA).
One example to reproduce the issue is:

```
@CustomObject('object-a', [
    ('id', IntegerProperty(required=True)),
    ('name', StringProperty(required=True)),
    ('object_a_children', ListProperty( ObjectA))
])
class ObjectA:
    pass
```

The ListProperty( ObjectA) part of the code returns me the error "Unresolved reference 'ObjectA' ".

Do I miss something? How we can create a CustomObject that has a list of the same type objects?

**Comment by asdimitriadis** [comment]
Finally, I figured out the solution.
If we want an object to contain a list of the same type object, we can use the "Property" parameter.
In the above example:
`@CustomObject('object-a', [
    ('id', IntegerProperty(required=True)),
    ('name', StringProperty(required=True)),
    ('object_a_children', ListProperty( Property))
])
class ObjectA:
    pass`


We can close this issue.

**Comment by rpiazza** [comment]
Hi @asdimitriadis,

I don't think your solution is going to provide what you were hoping for.  Is there a particular reason why you want to model this custom object to embed other objects of the same type?  In general, the STIX paradigm is to have relatively "flat" objects using "ref" properties (or a Relationship object) to connect different objects.  This obviously boils down to the classic design pattern decision - association vs composition.  python_stix2 doesn't support composition.

Using embedded relationships would we the best way to handle the design of your object.  I think it will give you what you are looking to support, unless I don't understand your use case.

```
  @CustomObject('object-a', [
      ('id', IntegerProperty(required=True)),
      ('name', StringProperty(required=True)),
      ('object_a_children', ListProperty( ReferenceProperty(valid_types='object-a'))
  ])
  class ObjectA:
      pass
```

**Comment by asdimitriadis** [comment]
Thanks for the response. I am closing the issue.
