### ISSUE TITLE
Report Object Reference throughs error when no argument passed

### ISSUE THREAD

**Issue by stbones** [oasis-open/cti-python-stix2#461]
Hi 
I have this below scenario where sometime no argument are passed to Object Reference under Report SDO. So, when I run below code I get this error. Any solution you can propose? 

from stix2 import Report

status = 0
r1 = Report(
    report_types=["campaign"],
    name="Bad Cybercrime",
    published="2016-04-06T20:03:00.000Z",
    object_refs=["indicator--a740531e-63ff-4e49-a9e1-a0a3eed0e3e7"] if status == 1 else None,
)

print(r1)

**ERROR**
MissingPropertiesError: No values for required properties for Report: (object_refs).

**Comment by rpiazza** [comment]
Hi @stbones,

object_refs is a required property, and STIX does not allow an empty list as the value of a property (see section 2.12 of the specification).  Have you considered not creating the Report object at all if it contains no objects?  Hope that helps!

**Comment by stbones** [comment]
@rpiazza  thank you, I have decided to pass some hard coded value. it will resolve this issue.

**Comment by stbones** [comment]
I am passing hard coded value
