### ISSUE TITLE
Howto use the v20 version of the workbench layer

### ISSUE THREAD

**Issue by diedel** [oasis-open/cti-python-stix2#478]
I just read in the docs that it's possible to import either stix.v20 or stix2.v21, but what about the workbench layer?

**Comment by clenk** [comment]
Hi @diedel, the workbench can only be used with the most recent STIX version, so currently stix2.v21. The goal was to keep the workbench as simple as possible so we haven't implemented support for other versions. The environment layer can be used with either v20 or v21, and the workbench is just shortcuts built on top of the environment layer. So if you need to use v20, you can use the environment layer and with a little extra code do anything the workbench can. Alternatively, v1.4.0 of this library is the last version in which v21 was the default, so you could use the workbench in that version.

**Comment by diedel** [comment]
Thank you. I'll rewrite the code, I think it's the best solution.
