### ISSUE TITLE
TAXIICollectionSource.query() only returns the first page

### ISSUE THREAD

**Issue by diedel** [oasis-open/cti-python-stix2#479]
I noticed that the TAXIICollectionSource methods query(), relationships(), ... only operates with the first page returned by the associated TAXII 2.0 server.

I did tests with a local Medallion server v1.1.0 which have a default max_page_size of 100.

By calling TAXIICollectionSource.query() I can get only 100/10000 objects. Also, when calling relationships(stix2_id) the results are limited to those 100 objects.

The only solution I found is increasing that max_page_size, so all objects are returned in one call.

**Comment by emmanvg** [comment]
It is likely that the same issue is present for a query to a TAXII 2.1, but thanks for bringing this up. We'll need to look at this...
