### ISSUE TITLE
[Question] How would i go about validating a STIX object represented as a dict

### ISSUE THREAD

**Issue by jullle3** [oasis-open/cti-python-stix2#487]
In my use case, i have clients who produce STIX 2.1 data, and i wish to utilize the very effective error handling and validators from the stix2 module on this data. How would i go about doing this? 

I can't seem to find a method to do this, but i might be wrong. I tried searching the stix2 docs, but without luck. 

 Thank you in advance.

**Comment by jullle3** [comment]
Since posting this, i have found https://github.com/oasis-open/cti-stix-validator.

However, the validator methods in stix2 are more precise and are thus still preferred.
For example, when creating an invalid malware object with is_family=True and no name, stix2 prints:
`stix2.exceptions.PropertyPresenceError: 'name' is a required property for malware families`

And cti-stix-validator prints:
`object is not valid under any of the given schemas`

**Comment by clenk** [comment]
Hi @jullle3, good question. If you pass your dict into `stix2.parse()` it will perform the validation by attempting to convert the dict into an instance of the python-stix2 class for its object type.

The less precise error messages from the validator are an unfortunate side effect of the library it uses for JSON schema validation. We can look into making the error message more clear for this use case though.

**Comment by jullle3** [comment]
Thank you. That makes sense. parse() is of much use to me, thank you:)
