### ISSUE TITLE
Broken version on PyPi?

### ISSUE THREAD

**Issue by pydima** [oasis-open/cti-python-stix2#51]
Hi! If I install stix2 with pip and try to parse json data from here https://github.com/oasis-open/cti-stix2-json-schemas/tree/master/examples/threat-reports I've got an error `ValueError: Can't parse unknown object type 'bundle'!`, but if I install this package with cloning from git and using `python setup.py install` everything works fine. So I wonder what is the problem here? Is it an old version on PyPi or what? Thanks!

**Comment by clenk** [comment]
Hi @pydima, thank you for the feedback. Yes, the version on PyPI is just old. This is an issue we fixed in #42 but have not included in a new release yet. We will release a new version soon. Thank you for your patience!
