### ISSUE TITLE
How to create a Grouping with context?

### ISSUE THREAD

**Issue by priamai** [oasis-open/cti-python-stix2#557]
Hi there,
need some help creating a Grouping

```
from stix2 import Grouping
from stix2.properties import OpenVocabProperty
from stix2 import IPv4Address

ip4 = IPv4Address(
    value="177.60.40.7",
    resolves_to_refs=["mac-addr--43f380fd-37c6-476d-8643-60849bf9240e"]
)

group = Grouping(name='alert',description='ciao',context=OpenVocabProperty('grouping-context-ov'),labels=['ciao'],object_refs=[ip4.id])
```

Reading the documentation:

![image](https://user-images.githubusercontent.com/57333254/190273122-7aab32fb-5b64-414b-883b-bf07de78304a.png)

What corresponding object should I use for the context?

**Comment by chisholm** [comment]
You can use any string you want since it's an open vocab.  The spec-defined values are included in a module stix2.v21.vocab.  E.g. `stix2.v21.vocab.GROUPING_CONTEXT_SUSPICIOUS_ACTIVITY`.

**Comment by clenk** [comment]
@priamai that looks like it is from the STIX version 1.2 specification. This library is for STIX version 2, which works differently. In STIX 2, open vocabularies can hold any string (thus being called "open"). The specification contains a list of values for the vocabulary as a starting point, and values from that list "should" be used as much as possible for interoperability, but any "arbitrary and unconstrained" string value could be used. There's not really a codified way to reference an externally defined custom vocabulary.

**Comment by priamai** [comment]
Hello @clenk you are totally right, I must have followed some links and didn't realised was indeed stix version 1.2.1 

I am reading this now: https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_vbsdt43uxrv0
For more context::

```
STIX vocabularies that have type names ending in '-ov', are "open": they provide a listing of common and industry accepted terms as a guide to the user but do not limit the user to that defined list. These vocabularies are referenced from the STIX Objects as type open-vocab and have a statement indicating which vocabulary should be used.


STIX vocabularies that have type names ending in '-enum' are "closed": the only valid values are those in the vocabulary. These vocabularies are referenced from the STIX Objects as type enum and have a statement indicating which enumeration must be used.

```

**Comment by RobNoVA** [comment]
@priamai The latest version of the 2.1 STIX specification (OASIS standard) is found here: https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html.  You were looking at the older Committee Specification 01 which was a precursor to the final approved version.

The section you were referencing is here: https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_vbsdt43uxrv0  Good news is there's no difference in text, just wanted to make sure you had the latest!

**Comment by priamai** [comment]
Thanks.
