### ISSUE TITLE
STIX2 json parse

### ISSUE THREAD

**Issue by ahadda5** [oasis-open/cti-python-stix2#558]
The library does not seem to know how to parse a bundle like  "enterprise-attack-11.3.json" on [github ](https://github.com/mitre-attack/attack-stix-data/tree/master/enterprise-attack)

The json has the form ```
{'type':'bundle',
'id':'bundle--8376c00f-48c6-4fc0-949f-06e8edd7c0a6',
'spec_version': '2.1',
'objects': a list of all 
```

Error is _stix2.exceptions.ParseError: Can't parse unknown object type 'x-mitre-collection'! For custom types, use the CustomObject decorator._

**Comment by clenk** [comment]
You should be able to avoid the error if you use `allow_custom=True` when you call `parse()`.
