### ISSUE TITLE
Improve Data Markings Ease-of-Use

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-python-stix2#56]
Some ideas I had while writing documentation, for how to make data markings a little easier to use:

- [ ] Maybe `StatementMarking()` should return a `MarkingDefinition` object and not require the user to create both a `MarkingDefinition` and `StatementMarking` object. Would a user ever create a `StatementMarking` object without also creating a `MarkingDefinition`?
- [x] We should add a shortcut to be able to call `add_markings()` (and the other marking functions) on STIX objects. So for example
	```indicator.remove_markings('marking--id')```
	instead of
	```markings.remove_markings(indicator, 'marking--id')```
As we implement these, be explicit that they return *new* versions of the objects since they are immutable.
- [x] stix2/\_\_init\_\_.py should import the functions from stix2.markings so they're in the top-level 
namespace.
- [x] `add_markings()` and `remove_markings()` should support passing in a `MarkingDefinition` object, not just an ID string.

**Comment by gtback** [comment]
My first thought would be to leave the object constructors the way they are, but add a function to create a StatementMarking and wrap it in a MarkingDefinition. Layer 1 shouldn't be too smart 😁 

I agree with the other three.

**Comment by emmanvg** [comment]
I think the same way as Greg. Ideas 2 - 4 are good addition to the code.
