### ISSUE TITLE
Add tests for FileSystem Data Stores, Sources, Sinks 

### ISSUE THREAD

**Issue by mbastian1135** [oasis-open/cti-python-stix2#58]
Specifically for adding/pushing STIX objects to these DataStores/Sinks as they can now be supplied with STIX content of a variety of forms

**Comment by mbastian1135** [comment]
FileSystem.get()/all_versions() break if do not find STIX object in filesystem

**Comment by gtback** [comment]
We should move the tests/ directory outside of the `stix2` package, so the tests (and associated test files) aren't included in releases. Also, let's split this issue into three (one for each type of DataStore). We can include moving the `tests/` directory with the FileSystem DataStore.
