### ISSUE TITLE
Granular marking constraint checking is incorrect

### ISSUE THREAD

**Issue by chisholm** [oasis-open/cti-python-stix2#586]
The STIX 2.1 spec [section 7.2.3](https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_robezi5egfdr) says that one cannot include both `lang` and `marking_ref` in a granular marking:

> Because each granular marking instance applies to either a language or a marking, one and only one of these properties MUST be present on each instance of a granular marking.

The library does not check this:

```python
import stix2

granular_marking = stix2.GranularMarking(
  lang="en",
  marking_ref=stix2.TLP_GREEN,
  selectors=["foo"]
)

granular_marking.fp_serialize(sys.stdout, indent=4)
```

results in:

```json
{
    "lang": "en",
    "marking_ref": "marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da",
    "selectors": [
        "foo"
    ]
}
```

which is invalid.

**Comment by rpiazza** [comment]
All STIX objects implemented in Python come with methods which check for constraint violations.

See https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/v21/common.py#L77 for the _check_object_constraints method related to GranularMarking.

The method _check_mutually_exclusive_properties on _STIXBase can be add to _check_object_constraints to fix this bug
