### ISSUE TITLE
Make list comprehensions more idiomatic

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-python-stix2#59]
We have several list comprehensions in the form:

```
[x for x in <iterable>]
```
These can be replaced with just `list(<iterable>)`

There are some more complex ones such as

```
[x for x in <iterable> if <some predicate on x>]
```

which can be replaced by `list(filter(lambda x: <predicate on x>, <iterable>))`

**Comment by gtback** [comment]
Note that some people think a listcomp is more idiomatic than `filter`, so it's debatable whether the latter examples should be changed. The former ones should, however.

**Comment by chisholm** [comment]
If the iterable is a sequence which supports slicing, the first can more compactly be done as:
```python
list_copy = original_list[:]
```
(of course,be sure a shallow copy is what you are after.)  For the second, I much prefer the comprehension.  Also for the latter (and in general), I prefer a generator expression, if you can get away with it.  Try not to make copies unnecessarily.

(P.s. I haven't actually searched the code to understand what contexts these constructs occur in.)

**Comment by gtback** [comment]
I've always used `list(X)` to consume a generator rather than `X[:]` (it also helps ensure the iterable is a list, if that's desired, rather than keeping the same iterable type). I'm not sure which more common/accepted/idiomatic, though.

I also agree that, where possible, generator expressions are preferable to list comprehensions, unless you need the list.
