### ISSUE TITLE
TAXIICollectionSource.get()/all_versions() - check id of returned objects

### ISSUE THREAD

**Issue by mbastian1135** [oasis-open/cti-python-stix2#66]
Add simple sanity check for the TAXIICollectionSource.get()/all_versions() calls, where the id of the STIX objects returned from the TAXII endpoint are checked to match

**Comment by mbastian1135** [comment]
Have this implemented locally. Was going to wait(?) for Brets external server to work.; or can just push.

**Comment by gtback** [comment]
Go ahead and push/make a PR now. I'm not sure the best way to test (and if there's a good way without an external server), but we should at least start thinking about it.

**Comment by rpiazza** [comment]
Ignoring Travis, are you using the cti_taxii_server to test in your own environment?

**Comment by mbastian1135** [comment]
I was not but I can.

**Comment by gtback** [comment]
Thanks, @rpiazza . Using medallion for local testing is 100% the way to go; testing via Travis will be a bit harder. We may need to set up some mock responses.
