### ISSUE TITLE
Update/check documentation guides for TAXIICollection and CompositeDataSource when TAXII server working

### ISSUE THREAD

**Issue by mbastian1135** [oasis-open/cti-python-stix2#67]
Currently the code examples have output that is not correct due to errors with the external TAXII server we are using for tests. Currently we are holding off as author of external TAXII server was notified of the errors and has stated they will address them; and implied sooner rather than later. (they should just need to be re-executed within jupyter notebook and output should correct when the TAXII server is patched)

**Comment by clenk** [comment]
Alternatively, we could run a server locally just to get the output into the Jupyter notebooks.

**Comment by clenk** [comment]
FYI, should be able to get objects by ID now on FreeTAXII, e.g. https://test.freetaxii.com:8000/osint/collections/d57c89ba-d128-4592-aca6-4ab6c1c097b3/objects/

**Comment by clenk** [comment]
Now getting the following error when using test.freetaxii.com:

> taxii2client.TAXIIServiceException: Unexpected Response Content-Type: application/vnd.oasis.stix+json; version=2.1; charset=utf-8

...which is interesting because the bundle that is returned has `"spec_version":"2.0"`.

Also, I believe it still supports only 2.1, not 2.0 content.

**Comment by johnwunder** [comment]
Yeah, I'm finding the same issue.

Might be useful to have some kind of option to ignore the MIME check and just parse it as if it's 2.0. Lots of people are doing this "preview STIX 2.1" stuff now.

**Comment by gtback** [comment]
Yep, thought the `taxii2client.TAXIIServiceException` is an error in the taxii-client, not python-stix2. We will (or at least can) check the `spec_version` of the Bundle in python-stix2, but the mime-type won't get passed through.

**Comment by mbastian1135** [comment]
@gtback looks like we fixed this. Im not seeing any erroneous doc guides and any TAXII content processing/checking enhancements would be implemented in the TAXII Client. Any objections to closing?

**Comment by gtback** [comment]
Yep, this can be closed.
