### ISSUE TITLE
Cannot serialize Bundle with object containing Custom Property

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-python-stix2#85]
To reproduce:

```python
 def test_custom_property_in_bundled_object():
        identity = stix2.Identity(
            name="John Smith",
            identity_class="individual",
            x_foo="bar",
            allow_custom=True,
        )
        bundle = stix2.Bundle(identity, allow_custom=True)

        assert bundle.objects[0].x_foo == "bar"
        assert '"x_foo": "bar"' in str(bundle)
```

Results in an error like this:

`TypeError: '<' not supported between instances of 'NoneType' and 'int'`

I believe this is because `stix2.utils.find_property_index` returns None for custom properties, which we should probably put at the end.

**Comment by emmanvg** [comment]
I am unable to reproduce this error with the example you provided.

**Comment by gtback** [comment]
I'm getting the error in Python 3, but not Python 2.

**Comment by emmanvg** [comment]
Using source code in `76-filesystem-bundles` branch??

Well, that's weird.

**Comment by emmanvg** [comment]
I tried running the tests in the `76-filesystem-bundles` branch. I get two failing errors, but these are related to datastores and it is completely different from what you are expressing on this issue. I tested with both Python 3 and 2, and I am still unable to reproduce this error. Do you have any local changes?

**Comment by emmanvg** [comment]
Made the changes. It should be good now. The changes are present in `76-filesystem-bundles` branch.

**Comment by clenk** [comment]
I can fix the remaining failing tests when I make the other changes for #76.

**Comment by emmanvg** [comment]
Sounds good!

**Comment by gtback** [comment]
We found this when working on #76, but I think the issue was present in the master branch. Seems like the fix was pretty easy, so it's fine that they are in the same branch.
