### ISSUE TITLE
Update package structure

### ISSUE THREAD

**Issue by emmanvg** [oasis-open/cti-python-stix2#91]
Per conversation in #79 we should start by updating the current package structure for STIX 2.0

**Comment by emmanvg** [comment]
What modules should be moved into the ``v20`` directory? Currently:
- sro.py
- sdo.py
- common.py (The only one that changes between versions is GranularMarking for now)
- core.py (Here the only thing that changes is the OBJ_MAP)

Still for consideration:
- obervables.py
- environment.py (Are environments version specific?)

Am I missing anything else?

**Comment by clenk** [comment]
I think observables should go in there too.

The `parse()` function will need to know which `OBJ_MAP` to look at. `parse()` is used in Environments and Data Stores/Sources/Sinks. Is there a way to avoid having to put all of those in the version subdirectories as well?

**Comment by rpiazza** [comment]
+1 - cyber observables are no different than SDO/SRO when it comes to STIX versions

**Comment by gtback** [comment]
Agree that `observables` should be in there. We can probably punt on `patterns` for now, since patterning won't be changing in STIX 2.1. I'd like to keep just one `parse()` function. Same with Environments (though there will need to be some logic in one or the other... or both... to detect/specify versions, the concept will remain the same across versions. Only things directly specified in the spec need to be versioned, IMO.

**Comment by emmanvg** [comment]
When you register a custom: sdo, observable, extension or marking. Should it be registered in all `OBJ` mappings?

**Comment by emmanvg** [comment]
What I had in mind was to also have a single CustomObject, CustomObservable, CustomMarking and CustomExtension. Now, I don't know how far we can get.

**Comment by gtback** [comment]
This brings up the point that we need a better answer for registering when there are multiple versions.

**Comment by emmanvg** [comment]
While talking to @clenk, I think it is better to leave it as it is because for objects properties might be different, etc. They should explicitly need to register it per version.
