### ISSUE TITLE
Custom properties not added when using allow_custom=True

### ISSUE THREAD

**Issue by emmanvg** [oasis-open/cti-python-stix2#98]

**Comment by emmanvg** [comment]
When using allow_custom=True, the new custom properties don't get added to the _properties dictionary. *This is not related to CustomObject.

**Comment by gtback** [comment]
Shouldn't `_properties` be a class-level variable? We wouldn't want to modify that. Also, do you mean the `Property` subclasses, or the values of the properties.

**Comment by emmanvg** [comment]
It's the _properties dict on _STIXBase. This issue only appears on Python 3 and it is related to #85.

**Comment by emmanvg** [comment]
That was the reason I had to change `object_properties()`, but the underlining behavior problem was not solved. This is to add custom properties to the _properties dict. While talking to @clenk I noticed the problem was still there.
