### ISSUE TITLE
Update DataStores, Sources, Sinks

### ISSUE THREAD

**Issue by emmanvg** [oasis-open/cti-python-stix2#99]
While working #98 I noticed even further problems with how the stores work. In addition to the fixes, I will adding:
- Proper ABC for DataStore, DataStore, and DataSink.
- The version positional argument was missing in a lot of places.

**Comment by clenk** [comment]
We also talked about moving `_composite_filters` to be the last argument for the methods that use it, since it is hidden and not meant for users to pass in.

**Comment by emmanvg** [comment]
Should `_store` move to the last argument as well? https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/sources/memory.py#L193

**Comment by gtback** [comment]
I really don't like passing "private" arguments. That's a design smell for me. Can we look at refactoring how we do this?
